

##Salmon#######################################################
name.1=iregex:.*(SalmonF).*
skins.1=1 2 3 4 5 6 7

name.2=iregex:.*(SalmonS).*
skins.2=8 9 10 11 12 13 14

name.3=iregex:.*(SockeyeF).*
skins.3=1
name.4=iregex:.*(SockeyeS).*
skins.4=9

name.5=iregex:.*(ChinookF).*
skins.5=2
name.6=iregex:.*(ChinookS).*
skins.6=13

name.7=iregex:.*(CohoF).*
skins.7=3
name.8=iregex:.*(CohoS).*
skins.8=11

name.9=iregex:.*(AtlanticF).*
skins.9=6
name.10=iregex:.*(AtlanticS).*
skins.10=14

name.11=iregex:.*(PinkF).*
skins.11=7
name.12=iregex:.*(PinkS).*
skins.12=8

name.13=iregex:.*(MasuF).*
skins.13=4
name.14=iregex:.*(MasuS).*
skins.14=10

name.15=iregex:.*(ChumF).*
skins.15=5
name.16=iregex:.*(ChumS).*
skins.16=12
##Salmon#######################################################

##Billfish#####################################################
name.17=iregex:.*(blue_marlin).*
skins.17=15

name.18=iregex:.*(swordfish).*
skins.18=18

name.19=iregex:.*(longbill_spearfish).*
skins.19=17

name.20=iregex:.*(hatchet_marlin).*
skins.20=16

name.21=iregex:.*(white_marlin).*
skins.21=19

name.22=iregex:.*(sailfish).*
skins22.=20

name.23=iregex:.*(billfish).*
skins.23=15 16 17 18 19 20

##Billfish#####################################################

##Tuna#########################################################
name.24=iregex:.*(yellowfin).*
skins.24=21

name.25=iregex:.*(bluefin).*
skins.25=24

name.26=iregex:.*(albacore).*
skins.26=22

name.27=iregex:.*(bigeye).*
skins.27=23

name.28=iregex:.*(blackfin).*
skins.28=25

name.29=iregex:.*(tuna).*
skins.29=21 22 23 24 25
##Tuna#########################################################

##Mahi#########################################################

##Default Mahi
name.30=iregex:.*(mahiD).*
skins.30=26 28 30 31 32 33 34

##Green Mahi
name.31=iregex:.*(mahiG).*
skins.31=29 35 36 37 38 39

##Blue Mahi
name.32=iregex:.*(mahiB).*
skins.32=27 40 41 42 43 44

##All Mahi Varients
name.33=iregex:.*(mahiA).*
skins.33=26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
##Mahi#########################################################

##Catfish######################################################

##All Catfish
name.34=iregex:.*(catfish).*
skins.34=45 46 47 48 49 50 51 52 53

##Channel
name.35=iregex:.*(channel).*
skins.35=45 46 47

##Redtailed
name.36=iregex:.*(cajaro).*
skins.36=48 49 50

##Blue Catfish
name.37=iregex:.*(forked_cat).*
skins.37=51 52 53
##Catfish######################################################


##biomes#######################################################
skins.38=1 2 3 4 5 6 7 45 46 47 48 49 50 51 52 53
biomes.38=river frozen_river

skins.39=15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44
biomes.39=cold_ocean deep_cold_ocean ocean deep_ocean warm_ocean deep_warm_ocean lukewarm_ocean deep_lukewarm_ocean

skins.40=8 9 10 11 12 13 14
biomes.40=frozen_ocean deep_frozen_ocean
##biomes#######################################################

